Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Text;
using WebBanThu.Areas.Admin.Models;
using Microsoft.AspNetCore.Session;
using Microsoft.AspNetCore.Http;
using WebBanThu.Models;

namespace WebBanThu.Controllers
{
	public class ProductController : Controller
	{
        private readonly IHttpContextAccessor _httpContextAccessor;

        public ProductController(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }
        string domain = "https://localhost:7253/";
		HttpClient client = new HttpClient();

		public async Task<IActionResult> Index()
		{
			ViewBag.Domain = domain;
			client.BaseAddress = new Uri(domain);
			string datajson = await client.GetStringAsync("api/Product/GET_ALL");
			List<ProductModel> products = JsonConvert.DeserializeObject<List<ProductModel>>(datajson);
			
            string datajson1 = await client.GetStringAsync("/api/Category/GET_ALL");
            List<CategoryModel> categories = JsonConvert.DeserializeObject<List<CategoryModel>>(datajson1);

            ViewBag.Products = products;
			ViewBag.Categories = categories;

            return View();
		}

        public async Task<IActionResult> Create()
		{

			client.BaseAddress = new Uri(domain);
			string datajson = await client.GetStringAsync("api/Category/GET_ALL");
			List<CategoryModel> categories = JsonConvert.DeserializeObject<List<CategoryModel>>(datajson);
			ViewBag.CategoryId = new SelectList(categories, "Id", "Tittle");
			return View();

		}
		[HttpPost]
		[ValidateAntiForgeryToken]

		public async Task<IActionResult> Create(ProductModel p, IFormFile fileimage)
		{
			//client.BaseAddress = new Uri(domain);

			//ProductModel product = new ProductModel();
			//using(var http = new HttpClient())
			//{
			//    var formdata = new MultipartFormDataContent();
			//    formdata.Add(new StringContent(p.Tittle), "Tittle");
			//    formdata.Add(new StringContent(p.Description), "Description");
			//    formdata.Add(new StringContent(p.Quantity.ToString()), "Quantity");
			//    formdata.Add(new StringContent(p.Price.ToString()), "Price");
			//    formdata.Add(new StringContent(p.CategoryId.ToString()), "CategoryId");
			//    formdata.Add(new StringContent(p.Isdelete.ToString()), "Isdelete");
			//    formdata.Add(new StreamContent(file.OpenReadStream()), "Picture", file.FileName);
			//    StringContent content = new StringContent(JsonConvert.SerializeObject(product), Encoding.UTF8, "application/json");
			//    using (var response = await http.PostAsync("api/Product/UploadFile", formdata))
			//    {
			//        string apiReponse = await response.Content.ReadAsStringAsync();
			//        product = JsonConvert.DeserializeObject<ProductModel>(apiReponse);
			//    }
			//}
			client.BaseAddress = new Uri(domain);
			var formdata = new MultipartFormDataContent();
			formdata.Add(new StringContent(p.Id.ToString()), "Id");
			formdata.Add(new StringContent(p.Tittle), "Tittle");
			formdata.Add(new StringContent(p.Description), "Description");
			formdata.Add(new StringContent(p.Quantity.ToString()), "Quantity");
			formdata.Add(new StringContent(p.Price.ToString()), "Price");
			formdata.Add(new StringContent(p.CategoryId.ToString()), "CategoryId");
			formdata.Add(new StringContent(p.Isdelete.ToString()), "Isdelete");
			formdata.Add(new StreamContent(fileimage.OpenReadStream()), "Picture", fileimage.FileName);
			var response = client.PostAsync("api/Product/UploadFile", formdata);
			return RedirectToAction("Index");
		}

		[HttpGet]
		public async Task<IActionResult> Edit(int id)
		{

			client.BaseAddress = new Uri(domain);
			ProductModel product = new ProductModel();
			string data = await client.GetStringAsync("api/Product/" + id);
			product = JsonConvert.DeserializeObject<ProductModel>(data);
            return View(product);

        }
		[HttpGet]
		public async Task<IActionResult> Details(int id)
		{
            ViewBag.Domain = domain;
            client.BaseAddress = new Uri(domain);
			ProductModel product = new ProductModel();
			string data = await client.GetStringAsync("api/Product/" + id);
			product = JsonConvert.DeserializeObject<ProductModel>(data);
            ViewBag.Product = product;
            ViewBag.ProductTittle = product.Tittle;
            return View();

        }
		[HttpPut]
		[ValidateAntiForgeryToken]

		public async Task<IActionResult> Edit(ProductModel p, IFormFile file)
		{
			ProductModel product = new ProductModel();
			using (var http = new HttpClient())
			{
				var formdata = new MultipartFormDataContent();
				formdata.Add(new StringContent(p.Tittle), "Tittle");
				formdata.Add(new StringContent(p.Description), "Description");
				formdata.Add(new StringContent(p.Quantity.ToString()), "Quantity");
				formdata.Add(new StringContent(p.Price.ToString()), "Price");
				formdata.Add(new StringContent(p.CategoryId.ToString()), "CategoryId");
				formdata.Add(new StringContent(p.Isdelete.ToString()), "Isdelete");
				formdata.Add(new StreamContent(file.OpenReadStream()), "Picture", file.FileName);
				StringContent content = new StringContent(JsonConvert.SerializeObject(product), Encoding.UTF8, "application/json");
				using (var response = await http.PutAsync("api/Product/UploadFile", formdata))
				{
					string apiReponse = await response.Content.ReadAsStringAsync();
					product = JsonConvert.DeserializeObject<ProductModel>(apiReponse);
				}
			}
			return RedirectToAction("Index");
		}
		[HttpDelete]
		public async Task<IActionResult> Delete(int ReservationId)
		{
			using (var httpClient = new HttpClient())
			{
				using (var response = await httpClient.DeleteAsync("https://localhost:7066/api/Product/" + ReservationId))
				{
					string apiResponse = await response.Content.ReadAsStringAsync();
				}
			}

			return RedirectToAction("Index");
		}



        
    }
}

Controllers/ServiceController.cs
using ApiPetShop.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Data;
using System.Text;
using WebBanThu.Areas.Admin.Models;
using WebBanThu.Models;

namespace WebBanThu.Controllers
{
    public class ServiceController : Controller
    {
        string domain = "https://localhost:7253/";
        HttpClient client = new HttpClient();

        public async Task<IActionResult> Index()
        {
            ViewBag.Domain = domain;
            client.BaseAddress = new Uri(domain);
            string datajson = await client.GetStringAsync("api/Service/GET_ALL");
            List<ServiceModel> services = JsonConvert.DeserializeObject<List<ServiceModel>>(datajson);

           

            ViewBag.Services = services;
           

            return View();
        }


        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {

            client.BaseAddress = new Uri(domain);
       
       
            try
            {
                ViewBag.Domain = domain;
                List<Service_DetailModel> list = new List<Service_DetailModel>();
                HttpResponseMessage response = client.GetAsync("api/Service_Detail/" + id).Result;

                if (response.IsSuccessStatusCode)
                {
                    string data1 = response.Content.ReadAsStringAsync().Result;
                    list = JsonConvert.DeserializeObject<List<Service_DetailModel>>(data1);
                    ServiceModel service = new ServiceModel();
                    HttpResponseMessage responseMessage = client.GetAsync("api/Service/"+id).Result;
                    string data = responseMessage.Content.ReadAsStringAsync().Result;
                    service = JsonConvert.DeserializeObject<ServiceModel>(data);
                    ViewBag.ServiceTittle = service.Tittle;
                    ViewBag.Service = service;
                    ViewBag.List = list;
                    List<TimeModel> times = new List<TimeModel>();
                    foreach(var i in list)
                    {
                        string datajson1 = await client.GetStringAsync("api/Time/" + i.IdTime);
                        TimeModel time = JsonConvert.DeserializeObject<TimeModel>(datajson1);
        
                        times.Add(time);
    
                    }
                    ViewBag.Times = times;
                    ViewBag.Times1 = new SelectList(times, "Id", "StartTime");

                }
                return View(list);
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }
            


            //string datajson1 = await client.GetStringAsync("api/Time");
            //List<TimeModel> times = JsonConvert.DeserializeObject<List<TimeModel>>(datajson1);
            //

            return View();

            
        }
        //[HttpGet]
        //public async Task<IActionResult> DatLich()
        //{
        //    return View();
        //}
        [HttpPost]
        [Authorize(Roles = "CUTOMER")]
        public async Task<IActionResult> DatLich(string email, int IdService, string Time, string SelectedTime)
        {
            client.BaseAddress = new Uri(domain);
            HttpResponseMessage datajson = client.GetAsync("api/Account/GetUseByEmail/" + email).Result;
            string data1 = datajson.Content.ReadAsStringAsync().Result;
            SignUpModel user = JsonConvert.DeserializeObject<SignUpModel>(data1);
            Service_CartModel p = new Service_CartModel
            {
                Time = SelectedTime,
                IdServie = IdService,
                IdUser = user.id,
                Quantity = 0,
                Price = 0,
                dateTime = DateTime.Now
            };
            try
            {

              
                string data = JsonConvert.SerializeObject(p);
                StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
                HttpResponseMessage responseMessage = client.PostAsync("api/Service_Cart", content).Result;
                if (responseMessage.IsSuccessStatusCode)
                {
                    TempData["successMessage"] = "Service_Cart Created";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }

            return View(p);
        }
        [Authorize(Roles = "CUTOMER")]
        public async Task<IActionResult> LichDaDat()
        {

            ViewBag.Domain = domain;
            client.BaseAddress = new Uri(domain);
            HttpResponseMessage datajson = client.GetAsync("api/Account/GetUseByEmail/" + User.Identity.Name).Result;
            string data1 = datajson.Content.ReadAsStringAsync().Result;
            SignUpModel user = JsonConvert.DeserializeObject<SignUpModel>(data1);
            List<Service_CartModel> Service_Details = new List<Service_CartModel>();
            List<Service_Cart> Service = new List<Service_Cart>();
            HttpResponseMessage responseMessage = client.GetAsync("api/Service_Cart/"+user.id).Result;
            if (responseMessage.IsSuccessStatusCode)
            {

                string data = responseMessage.Content.ReadAsStringAsync().Result;
                Service_Details = JsonConvert.DeserializeObject<List<Service_CartModel>>(data);
                foreach (var i in Service_Details)
                {
                    HttpResponseMessage datajson1 = client.GetAsync("api/Service/" + i.IdServie).Result;
                    string data2 = datajson1.Content.ReadAsStringAsync().Result;
                    ServiceModel service = JsonConvert.DeserializeObject<ServiceModel>(data2);
                    Service_Cart service_Cart = new Service_Cart { dateTime = i.dateTime, Name = user.Name, Title = service.Tittle, Time = i.Time };
                    Service.Add(service_Cart);
                }
            }
                

            return View(Service);
        }




    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">


    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto:wght@700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link href="/libUser/flaticon/font/flaticon.css" rel="stylesheet">

    <!-- /libUserraries Stylesheet -->
    <link href="/libUser/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="/Content/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="/Content/css/style.css" rel="stylesheet">
</head>

<body>

    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow-sm py-3 py-lg-0 px-3 px-lg-0">
        <div class="navbar-brand ms-lg-5">
            <h1 class="m-0 text-uppercase text-dark"><i class="bi bi-shop fs-1 text-primary me-3"></i>Pet Shop</h1>
        </div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse">
            <div class="navbar-nav ms-auto py-0">
                <a href="/" class="nav-item nav-link">TRANG CHỦ</a>
                <a asp-controller="Service" asp-action="Index" class="nav-item nav-link">DỊCH VỤ</a>
                <a asp-controller="Product" asp-action="Index" class="nav-item nav-link">THÚ CƯNG</a>
                <a asp-controller="Service" asp-action="LichDaDat" class="nav-item nav-link">XEM LỊCH</a>
                <a asp-controller="Home" asp-action="DanhSachBillByKH" class="nav-item nav-link">XEM HÓA ĐƠN</a>
                <a asp-controller="ShoppingCart" asp-action="Cart"  class="nav-item nav-link bg-primary text-white px-5 ms-lg-5">GIỎ HÀNG<i class="bi bi-arrow-right"></i></a>
            </div>
        </div>
    </nav>
    <!-- Navbar End -->

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Footer Start -->
    <div class="container-fluid bg-light mt-5 py-5">
        <div class="container pt-5">
            <div class="row g-5">

                <div class="col-lg-3 col-md-6">
                    <h5 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">Quick Links</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-body mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Home</a>
                        <a class="text-body mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>About Us</a>
                        <a class="text-body mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Our Services</a>
                        <a class="text-body mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Meet The Team</a>
                        <a class="text-body mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Latest Blog</a>
                        <a class="text-body" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Contact Us</a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h5 class="text-uppercase border-start border-5 border-primary ps-3 mb-4">Popular Links</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-body mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Home</a>
                        <a class="text-body mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>About Us</a>
                        <a class="text-body mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Our Services</a>
                        <a class="text-body mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Meet The Team</a>
                        <a class="text-body mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Latest Blog</a>
                        <a class="text-body" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Contact Us</a>
                    </div>
                </div>


            </div>
        </div>
    </div>
    <div class="container-fluid bg-dark text-white-50 py-4">
        <div class="container">
        </div>
    </div>
    <!-- Footer End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-primary py-3 fs-4 back-to-top"><i class="bi bi-arrow-up"></i></a>


    <!-- JavaScript /libUserraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/libUser/easing/easing.min.js"></script>
    <script src="/libUser/waypoints/waypoints.min.js"></script>
    <script src="/libUser/owlcarousel/owl.carousel.min.js"></script>
    <script src="/content/js/site.js"></script>
    <script src="/content/js/cart.js"></script>
    <!-- Template Javascript -->
    <script src="/Content/js/main.js"></script>
    @await RenderSectionAsync("scripts", required: false)
</body>

</html>