Areas/Admin/Controllers/AdminServiceController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using WebBanThu.Areas.Admin.Models;

namespace WebBanThu.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "ADMIN")]
    //[Authorize]
    public class AdminServiceController : Controller
    {
        string domain = "https://localhost:7253/";
        HttpClient client = new HttpClient();

        public async Task<IActionResult> Index()
        {
            ViewBag.Domain = domain;
            client.BaseAddress = new Uri(domain);
            string datajson = await client.GetStringAsync("api/Service/GET_ALL");

            List<ServiceModel> Services = JsonConvert.DeserializeObject<List<ServiceModel>>(datajson);

            return View(Services);

        }

        [HttpGet]

        public async Task<IActionResult> Create()

        {
           
            return View();

        }
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]


        public async Task<IActionResult> Create(ServiceModel p, IFormFile file)

        {

            try
            {
                client.BaseAddress = new Uri(domain);
                var formdata = new MultipartFormDataContent();
                //formdata.Add(new StringContent(p.Id.ToString()), "Id");
                formdata.Add(new StringContent(p.Tittle), "Tittle");

                formdata.Add(new StringContent(p.Description), "Description");

                formdata.Add(new StreamContent(file.OpenReadStream()), "Picture", file.FileName);
                formdata.Add(new StringContent(p.Price.ToString()), "Price");
                formdata.Add(new StringContent(p.Isdelete.ToString()), "Isdelete");
         
                HttpResponseMessage response = client.PostAsync("api/Service/uploadfile", formdata).Result;
                if (response.IsSuccessStatusCode)
                {
                    TempData["successMessage"] = "Service created";
                    return RedirectToAction("Index");
                }
                return View();
            }

            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }




        }


        [HttpPost]

        public async Task<IActionResult> Edit(int id, ServiceModel p, IFormFile file)

        {
            try
            {
                client.BaseAddress = new Uri(domain);
                var formdata = new MultipartFormDataContent();
                formdata.Add(new StringContent(p.Id.ToString()), "Id");
                formdata.Add(new StringContent(p.Tittle), "Tittle");

                formdata.Add(new StringContent(p.Description), "Description");

                formdata.Add(new StreamContent(file.OpenReadStream()), "Picture", file.FileName);
                formdata.Add(new StringContent(p.Price.ToString()), "Price");
                formdata.Add(new StringContent(p.Isdelete.ToString()), "Isdelete");
          

                //string data = JsonConvert.SerializeObject(formdata);
                //StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
                HttpResponseMessage response = client.PutAsync("api/Service/updateloadFile/" + id, formdata).Result;
                if (response.IsSuccessStatusCode)
                {
                    TempData["successMessage"] = "Service edit";
                    return RedirectToAction("Index");
                }
                return View();
            }

            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }

        }
        [HttpGet]


        public async Task<IActionResult> Edit(int id)

        {


            try
            {
                ViewBag.Domain = domain;
                client.BaseAddress = new Uri(domain);
                ServiceModel Service = new ServiceModel();
   
                HttpResponseMessage response = client.GetAsync("api/Service/" + id).Result;
                if (response.IsSuccessStatusCode)
                {
                    string data = response.Content.ReadAsStringAsync().Result;

                    Service = JsonConvert.DeserializeObject<ServiceModel>(data);

                }
                return View(Service);
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }
        }
        [HttpGet]

        public async Task<IActionResult> Details(int id)

        {

            try
            {
                ViewBag.Domain = domain;
                client.BaseAddress = new Uri(domain);
 
                ServiceModel Service = new ServiceModel();
                HttpResponseMessage response = client.GetAsync("api/Service/"+id).Result;
                if (response.IsSuccessStatusCode)
                {
                    string data = response.Content.ReadAsStringAsync().Result;
                    Service = JsonConvert.DeserializeObject<ServiceModel>(data);
                }
                return View(Service);
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }

        } 

        public async Task<IActionResult> IndexDetail(int id)

        {
            
            try
            {
                ViewBag.Domain = domain;
                client.BaseAddress = new Uri(domain);
                List<Service_DetailModel> list = new List<Service_DetailModel>();
                HttpResponseMessage response = client.GetAsync("api/Service_Detail/" + id).Result;
            
                if (response.IsSuccessStatusCode)
                {
                    string data = response.Content.ReadAsStringAsync().Result;
                    list = JsonConvert.DeserializeObject<List<Service_DetailModel>>(data);
                }
                return View(list);
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }

        }

        [HttpGet]

        public async Task<IActionResult> Delete(int Id)

        {
            try
            {
                ViewBag.Domain = domain;
                client.BaseAddress = new Uri(domain);
                ServiceModel Service = new ServiceModel();
                HttpResponseMessage response = client.GetAsync("api/Service/" + Id).Result;
                if (response.IsSuccessStatusCode)
                {
                    string data = response.Content.ReadAsStringAsync().Result;
                    Service = JsonConvert.DeserializeObject<ServiceModel>(data);

                }
                return View(Service);
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }
        }
        [HttpPost, ActionName("Delete")]

        public async Task<IActionResult> DeleteConfirmed(int id)

        {
            try
            {
                client.BaseAddress = new Uri(domain);

                HttpResponseMessage response = client.DeleteAsync("api/Service/" + id).Result;
                if (response.IsSuccessStatusCode)
                {
                    TempData["successMessage"] = "Service delete";
                    return RedirectToAction("Index");
                }
                return View();
            }

            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }

        }
    }
}

Areas/Admin/Views/AdminService/Create.cshtml
@model WebBanThu.Areas.Admin.Models.ServiceModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Thêm Mới Dịch Vụ</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form asp-action="Create" enctype="multipart/form-data">
        <div class="card-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Tittle" class="control-label"></label>
                <input asp-for="Tittle" class="form-control" />
                <span asp-validation-for="Tittle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input type="file" name="file"nae class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Isdelete" class="control-label"></label>
                <input asp-for="Isdelete" class="form-control" />
                <span asp-validation-for="Isdelete" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </form>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Views/AdminService/Delete.cshtml
@model WebBanThu.Areas.Admin.Models.ServiceModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Xóa</h1>

<h3>Bạn Chắc Muốn Xóa Chứ</h3>
<div>
 
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tittle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tittle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            <img src="@ViewBag.Domain@Html.DisplayFor(model => model.Image)" alt="hinh ảnh" style="width:200px;height:200px" />
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Isdelete)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Isdelete)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Areas/Admin/Views/AdminService/Details.cshtml
@model WebBanThu.Areas.Admin.Models.ServiceModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Chi Tiết</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tittle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tittle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Isdelete)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Isdelete )
           
        </dd>
    </dl>
</div>
<div>
    @*@Html.ActionLink("Chi tiết lịch", "IndexDetail", new { id = Model.Id})*@
    @*@Html.ActionLink("Edit", "Edit", new { id = @Html.DisplayFor(model => model.Id)}) |*@
    <a asp-action="Index">Back to List</a>
</div>
<div >
    <iframe src="@Url.Action("IndexDetail", "AdminService", new { id = Model.Id  })" style="width:800px;height:800px"></iframe> 
</div>
   

Areas/Admin/Views/AdminService/Edit.cshtml
@model WebBanThu.Areas.Admin.Models.ServiceModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Sửa</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form asp-action="Edit" enctype="multipart/form-data">
        <div class="card-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tittle" class="control-label"></label>
                <input asp-for="Tittle" class="form-control" />
                <span asp-validation-for="Tittle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Isdelete" class="control-label"></label>
                <input asp-for="Isdelete" class="form-control" />
                <span asp-validation-for="Isdelete" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </form>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Views/AdminService/Index.cshtml
@model IEnumerable<WebBanThu.Areas.Admin.Models.ServiceModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


<section class="content">
    <div class="container-fluid">
        <h1>Quản Lý Dịch Vụ</h1>
        <a asp-action="Create" class="btn btn-success btn-icon-split">
            <span class="icon text-white-50"></span>
            <span class="text">Thêm Dịch Vụ</span>
        </a>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Id)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Tittle)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Description)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Image)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Price)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Isdelete)
                        </th>
                        <th>
                            Thao Tác
                        </th>
                        <th></th>
                    </tr>
                </thead>
                            <tfoot>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Id)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Tittle)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Description)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Image)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Price)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Isdelete)
                        </th>
                        <th>
                            Thao Tác
                        </th>
                        <th></th>
                    </tr>
                </tfoot>
                            <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Tittle)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td>
                                <img src="@ViewBag.Domain@item.Image" alt="hinh ảnh" style="width:200px;height:200px">
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Price)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Isdelete)
                            </td>

                            <td>
                                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-info btn-icon-split">
                                    <span class="icon text-white-50">
                                        <i class="fas fa-info-circle"></i>
                                    </span>
                                    <span class="text">Sửa</span>
                                </a>
                                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-danger btn-icon-split">
                                    <span class="icon text-white-50">
                                        <i class="fas fa-trash"></i>
                                    </span>
                                    <span class="text">Xem</span>
                                </a>
                                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-warning btn-icon-split">
                                    <span class="icon text-white-50">
                                        <i class="fas fa-exclamation-triangle"></i>
                                    </span>
                                    <span class="text">Xóa</span>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
                        </table>
                    </div>
                 </div>
              </div>
        </div>
    </div>
</section>

Areas/Admin/Views/AdminService/IndexDetail.cshtml
@model IEnumerable<WebBanThu.Areas.Admin.Models.Service_DetailModel>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>IndexDetail</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebBanThu.styles.css" asp-append-version="true" />
</head>
<body>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SoLuongCa)
            </th>
            <th>
                 Giờ 
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NgayThucHien)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            
            <td>
                @Html.DisplayFor(modelItem => item.SoLuongCa)
            </td>
             <td>
                       
             </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayThucHien)
            </td>
        
        </tr>
}
    </tbody>
</table>
 <script src="~/lib/jquery/dist/jquery.min.js"></script>
 <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
 <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>